### PR TITLE
Updates to get the car moving

### PR DESCRIPTION
**Pull request by jwdunn1**
Not every pull request needs to be documented like this, but I thought it might help to explain some of the changes you'll see further down in the code associated with these notes (on the changes tab).

With a first pass on the project files, I expanded on a couple of TODO's and applied a fix to reduce the quantity of communication from controller to simulator. To test, clone this branch and follow the usage instructions in the readme. The branch should compile cleanly and the car in the simulator should move forward without steering. If this pull request tests correctly and is accepted, we'll be able to close issue #3 and we will all have a master branch that, at the very least, moves the car in the simulator. (Hey, it's a start!)

**Drive-by-wire node**
I've added an instantiation of a Controller object. (but the class will need to be further defined in twist_controller.py to determine throttle, brakes, and steering.) I also subscribed to a few topics we'll need. Presently publishing the stub value of full throttle, no brake, no steering.

**Waypoint updater node**
In some early preparation of this node, based on the last two projects, I added some assist/support routines to locate the nearest next waypoint and determine its distance. Also, assembled an initial implementation of the pose callback to determine position and orientation.

**Framework fixes**
The while loop addition at line 57 in bridge.py prevents division by zero later on at line 113. (There may be a more elegant way to do this. It is recommended to loop on get_time until ROS knows the current time.)

The simulator was lagging poorly. The car would not move until the controller was stopped - THEN it would start moving. Investigated Slack discussion and found issue (self-driving-car-sim/issues/53). To mitigate the lag, the message queue is reduced to the latest message. This affects server.py and pure_pursuit.cpp. Also, the rate of transmission is reduced in waypoint_loader.py. We can increase if necessary.

**Updated repo readme**
Changed the link from project intro to our project overview.
Usage steps are hopefully more clear.

### CODE REVIEW

**Comment by yosoufe** [comment]
Why did you change the `server.py` and `pure_pursuit.cpp`?? Are we supposed to do that?

**Comment by jwdunn1** [comment]
As mentioned in my preface to this pull request, the `server.py` and `pure_pursuit.cpp` were changed to improve simulator performance. As noted by a number of people on Slack, the simulator slows down due to an overload in repetitious messages. Only one message is required per communication cycle. This is documented in the Udacity simulator open issue referenced above (#53). No need to overload the simulator or the real car. As to whether we should or should not modify these files, the classroom project overview states, "feel free to implement the project how you please!" If these files are not updated, the car will not move. If there is an alternative workaround, or even an upstream fix, we can always back out the changes.

**Review by yosoufe — APPROVED** [review]
you can use `float("inf")` as the largest value when you are sorting or comparing

in assist.py and waypoint_updater:
Maybe it is better to define a transformation once, then transform all the points to the vehicle coordinate and compare the distances. In this way all the sin and cos s are calculated once.

**Comment by jwdunn1** [comment]
Thank you for the review and suggestions! It is helpful that they are archived here for future reference as we proceed with the project.

**Pull request merged**
